### ISSUE TITLE
Timestamp format for logging not sufficient for analyis

### ISSUE THREAD

**Issue by stdx** [zlElo/Froggius#1]
Based on

`[DBG] [26/04/2024 12:04:21] Read config file...`

as an example:

Log date format is not customizable. For most use cases something like 
```
2024-04-16 20:48:39.505 INFO  ...
```

would be far easier to read and parse. It also would contain inherent sorting (YYYY-MM-dd). Also the granualirity is much finer. Most execution steps happen in ms instead of seconds. Too much information is lost when logging statements in seconds only.

**Comment by stdx** [comment]
So basically my suggestion is:
* configurable time format
* better default

**Comment by zlElo** [comment]
Hey @stdx I implemented your suggestion in this commit:https://github.com/zlElo/Froggius/commit/c82dd7e396255831906c1b3b8cdb4c27b9a3839f

Greets 🍕
