### ISSUE TITLE
Custom log levels do not adhere to standard log level names

### ISSUE THREAD

**Issue by stdx** [zlElo/Froggius#2]
Based on

`[DBG] [26/04/2024 12:04:21] Read config file...`

as an example:

Why don't stick to default levels for logging like DEBUG, INFO, ERROR? Do you want to save disk space or is that some kind of pythonic way I am not aware of?

**Comment by zlElo** [comment]
This format is the standard. This means everything is always correctly indented. To save disk space is a nice side effect 👍🏼
